export const COUNTRY_PHONE_PREFIXES: Record<string, string> = {
  'España': '+34',
  'Spain': '+34',
  'México': '+52',
  'Mexico': '+52',
  'Argentina': '+54',
  'Colombia': '+57',
  'Chile': '+56',
  'Perú': '+51',
  'Peru': '+51',
  'Ecuador': '+593',
  'Venezuela': '+58',
  'Uruguay': '+598',
  'Paraguay': '+595',
  'Bolivia': '+591',
  'Costa Rica': '+506',
  'Panamá': '+507',
  'Panama': '+507',
  'Guatemala': '+502',
  'Honduras': '+504',
  'El Salvador': '+503',
  'Nicaragua': '+505',
  'República Dominicana': '+1',
  'Cuba': '+53',
  'Puerto Rico': '+1',
  'Estados Unidos': '+1',
  'United States': '+1',
  'Portugal': '+351',
  'Francia': '+33',
  'France': '+33',
  'Italia': '+39',
  'Italy': '+39',
  'Alemania': '+49',
  'Germany': '+49',
  'Reino Unido': '+44',
  'United Kingdom': '+44',
  'Brasil': '+55',
  'Brazil': '+55',
  'Andorra': '+376',
};

export const getPhonePrefixForCountry = (country?: string | null): string => {
  if (!country) return '+34';
  return COUNTRY_PHONE_PREFIXES[country] || '+34';
};

export const COMMON_PREFIXES = [
  { prefix: '+34', country: 'España' },
  { prefix: '+52', country: 'México' },
  { prefix: '+54', country: 'Argentina' },
  { prefix: '+57', country: 'Colombia' },
  { prefix: '+56', country: 'Chile' },
  { prefix: '+51', country: 'Perú' },
  { prefix: '+593', country: 'Ecuador' },
  { prefix: '+58', country: 'Venezuela' },
  { prefix: '+598', country: 'Uruguay' },
  { prefix: '+55', country: 'Brasil' },
  { prefix: '+1', country: 'EE.UU.' },
  { prefix: '+351', country: 'Portugal' },
  { prefix: '+33', country: 'Francia' },
  { prefix: '+39', country: 'Italia' },
  { prefix: '+44', country: 'Reino Unido' },
  { prefix: '+49', country: 'Alemania' },
  { prefix: '+376', country: 'Andorra' },
];
